spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: hello
    url: jdbc:mysql://localhost:3306/jrtp23
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    


      
      